# Generated by Django 5.2.7 on 2026-02-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='current_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
